version: '3.8'

services:
  db-registration:
    image: postgres:14
    container_name: db-registration
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_registration:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  web-registration:
    build: .
    container_name: web-registration
    command: gunicorn --bind 0.0.0.0:8001 --workers 3 ohio.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db-registration
    restart: unless-stopped

volumes:
  postgres_data_registration:
  static_volume:
